data:
  nodes_path: "elliptic_bitcoin_dataset/elliptic_txs_features.csv"
  edges_path: "elliptic_bitcoin_dataset/elliptic_txs_edgelist.csv"
  labels_path: "elliptic_bitcoin_dataset/elliptic_txs_classes.csv"

  temporal_split:
    train: [1, 34]
    val:   [35, 41]
    test:  [42, 49]

  random_split:
    test_size: 0.3
    val_frac_of_test: 0.5
    seed: 42
