active_learning:

  # Sequential temporal grouping
  sequential:
    train_min_t: 1            # first train time step (inclusive)
    train_max_t: 34           # last  train time step (inclusive)

  training_params:
    MLP:
      local:
        dag:
          max_epochs: 50
          patience: 5
        undirected:
          max_epochs: 50
          patience: 5
      all:
        dag:
          max_epochs: 50
          patience: 5
        undirected:
          max_epochs: 50
          patience: 5

    GCN:
      local:
        dag:
          max_epochs: 50
          patience: 5
        undirected:
          max_epochs: 50
          patience: 5
      all:
        dag:
          max_epochs: 50
          patience: 5
        undirected:
          max_epochs: 50
          patience: 5

    EVOLVEGCN:
      local:
        dag:
          max_epochs: 50
          patience: 5
        undirected:
          max_epochs: 50
          patience: 5
      all:
        dag:
          max_epochs: 50
          patience: 5
        undirected:
          max_epochs: 50
          patience: 5

    DYSAT:
      local:
        dag:
          max_epochs: 50
          patience: 5
        undirected:
          max_epochs: 50
          patience: 5
      all:
        dag:
          max_epochs: 50
          patience: 5
        undirected:
          max_epochs: 50
          patience: 5
