training_defaults:
  early_stopping:
    eps: 0.003
    patience: 10
    max_epochs: 100


training_params:
  MLP:
    local:
      dag:
        max_epochs: 170
        patience: 15
      undirected:
        max_epochs: 170
        patience: 15
    all:
      dag:
        max_epochs: 170
        patience: 15
      undirected:
        max_epochs: 170
        patience: 15

  GCN:
    local:
      dag:
        max_epochs: 170
        patience: 15
      undirected:
        max_epochs: 170
        patience: 15
    all:
      dag:
        max_epochs: 170
        patience: 15
      undirected:
        max_epochs: 170
        patience: 15

  EVOLVEGCN:
    local:
      dag:
        max_epochs: 170
        patience: 15
      undirected:
        max_epochs: 170
        patience: 15
    all:
      dag:
        max_epochs: 170
        patience: 15
      undirected:
        max_epochs: 170
        patience: 15

  DYSAT:
    local:
      dag:
        max_epochs: 170
        patience: 15
      undirected:
        max_epochs: 170
        patience: 15
    all:
      dag:
        max_epochs: 170
        patience: 15
      undirected:
        max_epochs: 170
        patience: 15
