training_defaults:
  early_stopping:
    eps: 0.003
    patience: 10
    max_epochs: 100


training_params:
  MLP:
    local:
      dag:
        max_epochs: 200
        patience: 60
      undirected:
        max_epochs: 200
        patience: 60
    all:
      dag:
        max_epochs: 200
        patience: 60
      undirected:
        max_epochs: 200
        patience: 60

  GCN:
    local:
      dag:
        max_epochs: 150
        patience: 45
      undirected:
        max_epochs: 150
        patience: 45
    all:
      dag:
        max_epochs: 150
        patience: 45
      undirected:
        max_epochs: 150
        patience: 45

  EVOLVEGCN:
    local:
      dag:
        max_epochs: 35
        patience: 10
      undirected:
        max_epochs: 29
        patience: 8
    all:
      dag:
        max_epochs: 26
        patience: 7
      undirected:
        max_epochs: 20
        patience: 6

  DYSAT:
    local:
      dag:
        max_epochs: 18
        patience: 5
      undirected:
        max_epochs: 14
        patience: 5
    all:
      dag:
        max_epochs: 18
        patience: 5
      undirected:
        max_epochs: 13
        patience: 5
