models:
  GCN:
    model:
      hidden_channels: 64
      dropout: 0.5
    training:
      lr: 0.02
      weight_decay: 0.002

  MLP:
    model:
      hidden1: 128
      hidden2: 64
      dropout: 0.5
    training:
      lr: 0.05
      weight_decay: 0.0005

  EVOLVEGCN:
    model:
      hidden_channels: 128
      dropout: 0.5
    training:
      lr: 0.001
      weight_decay: 0.0005

  DYSAT:
    model:
      struct_hidden: 128
      struct_out: 128
      L: 5
      temp_heads: 4
      temp_dropout: 0.1
    training:
      lr: 0.0005
      weight_decay: 0.0001
